global:
  keyVaultUri: default
  OTELServiceName: Swo.Extensions.AWS
  AppInsightsConnectionString: ZGVmYXVsdA==
  ServiceName: default
  MpPortalBaseUrl: default
  MpBaseUrl: default
  MpApiToken: ZGVmYXVsdA==
  ConfigJson: ZGVmYXVsdA==
  DjangoSecretKey: ZGVmYXVsdA==
  MpProductsIds: default
  WebhookSecretKeys: ZGVmYXVsdA==
  AirTableApiToken: ZGVmYXVsdA==
  AirTablePoolBase: "{}"
  AirTableNotificationPoolBase: "{}"
  MsTeamsWebhookUrl: ZGVmYXVsdA==
  EmailNotificationsSender: default
  EmailNotificationsEnabled: "1"
  CrmOauthUrl: default
  CrmClientId: default
  CrmClientSecret: ZGVmYXVsdA==
  CrmAudience: default
  CcpOauthUrl: default
  CcpClientId: default
  CcpOauthScope: default
  CcpOauthCredentialsScope: default
  CcpApiBaseUrl: default
  MpSetupContextsFunc: swo_aws_extension.flows.fulfillment.base.setup_contexts
  MpOrdersApiPollingIntervalSecs: 60
  CrmApiBaseUrl: default
  CcoApiBaseUrl: default
  CcoOauthUrl: default
  CcoClientId: default
  CcoClientSecret: ZGVmYXVsdA==
  CcoAudience: default
  CcoManufacturerCode: default
  SvcProvisioningApiBaseUrl: default
  SvcProvisioningOauthUrl: default
  SvcProvisioningClientId: default
  SvcProvisioningClientSecret: ZGVmYXVsdA==
  SvcProvisioningAudience: default
  AwsOpenIdScope: default
  AwsRegion: us-east-1
  AirTableBases: default
  CcpKeyVaultSecretName: default
  ExtMinimumMpaThreshold: 1
  FfcOperationsSecret: ZGVmYXVsdA==
  FfcOperationsApiBase: default
  FfcOperationsSub: default
  MpNotifyCategories: "{}"
  MpInitializer: swo_aws_extension.initializer.initialize
  ManagementRole: default
  BillingRole: swo/mpt/SWOExtensionBillingRole
  ApnRoleName: default
  ApnAccountId: default
  replicaCountAPI: 1
  replicaCountWorker: 1
  registryUrl: ""
  AzureTenantId: ""
  QueryingTimeoutDays: 4
  CloudOrchestratorApiBaseUrl: default
  AwsSesCredentials: ZGVmYXVsdA==
  AwsSesRegion: default
  DeployServicesFeatureRecipients: default
  CustomerRolesQueryingTimeoutDays: 2
  AzureStorageConnectionString: ZGVmYXVsdA==
  AzureStorageContainer: private
  AzureStorageSasExpiryDays: 7
  ReportInvitationsFolder: reports/aws/billing-transfer-invitations/
  ReportBillingFolder: reports/aws/billing/
  MptToolStorageType: default
  MptToolStorageAirtableBaseId: default
  MptToolStorageAirtableTableName: default
  PendingOrdersInformationReportPageId: default
  ConfluenceUser: default
  ConfluenceToken: ZGVmYXVsdA==
  ConfluenceBaseUrl: default
  PlSChargePercentage: "5.0"

  cronjobs:
    order-querying:
      schedule: ""
      command: order_querying_processor
    sync-agreements:
      schedule: ""
      command: synchronize_agreements
    ccp-secret:
      schedule: ""
      command: refresh_ccp_openid_secret
    generate-billing:
      schedule: ""
      command: generate_billing_journals
    sync-finops:
      schedule: ""
      command: synchronize_finops_accounts
    invitations-report:
      schedule: ""
      command: create_invitations_report
    pending-report:
      schedule: ""
      command: create_pending_orders_information_report
